# Generated by Django 4.2.23 on 2025-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
