# Generated by Django 4.2.23 on 2025-09-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_book_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Publicly accessible URL of the cover image (Google Drive link)', max_length=500, null=True),
        ),
    ]
